== Determining string length of user input
I think I need to fill `buffer` with zeros first and then determine its
length after the read syscall

== Database ?
Maybe just save to raw binary file and read it later? Create vriables in `.data`
that are ids for the position in the data. You could then create similar
versions of that data in `.bss` that get read into memory on a read file. Data
is writen into a file, first it writes the 8-bit id, then it writes the 8-bit
length of the data, and then the data. I'm going to need a way to have dynamic
memory, maybe using `extern malloc` ? Or allocating you own memory? Seems a bit
in depth.

- https://stackoverflow.com/questions/5561022/how-to-dynamically-allocate-memory-for-an-array-in-assembly-8086-using-nasm[memory allocation]
- https://baptiste-wicht.com/posts/2011/11/dynamic-memory-allocation-intel-assembly-linux.html[memory allocation intel assemly linux]
- https://stackoverflow.com/questions/22919019/unable-to-allocate-memory-with-mmap-in-x86-linux-assembly-language[mmap]
- https://stackoverflow.com/questions/22586532/assembly-x86-brk-call-use[brk]
- https://www.youtube.com/watch?v=XV5sRaSVtXQ[brk]
- https://sourceware.org/glibc/wiki/MallocInternals[malloc]
- https://stackoverflow.com/questions/48672864/how-to-use-malloc-and-free-in-64-bit-nasm[malloc]
- https://www.sobyte.net/post/2022-03/mmap/[mmap]

I'm going to be allocating small chunks of memory so I'll probably want to use
`brk`.

== Writing to a file?
open file wiht sys_open. write to file descriptor with sys_write?

== Stack frame
 I thinking pushing sometimes causes segfaults because it unaligns the stack,
 making it not 16-byte aligned. It seems that is the case, doing another push
 seems to realign the stack

== TODO

create theses functions:

- string_cmp
- io_printf

== To see memory address of strarr

[source, gdb]
----
x/s * <address of strarr>
----

== Memory delimiter
The delemiter for memory will be the newline ('\n') character

[source, gdb]
----
(gdb) x/s * 0x4040e6
0x405000:       "joe\n43\n"
----


== Moving through array

The code below moves takes the address of memory in the heap and incrments it to
get a value in the array. This assumes rax is an offset value. The array address
is in rbx.
[source, nasm]
----
mov rbx, strarr
mov rbx, [rbx]

lea rbx, [rbx + rax]
; or
;add rcx, rax ; increment to get value in arary
----
